### ISSUE TITLE
User-created Machine Accounts are not parsed properly as Computers

### ISSUE THREAD

**Issue by 0x0db5** [c3c/ADExplorerSnapshot.py#11]
User-created machine accounts (e.g. with new-adcomputer cmdlet) are not included in the parsed output from AD Explorer snapshot. Per source code, it appears the object is not parsed correctly due to a lack of the "dnshostname" attribute for Computer objects created this way.

https://github.com/c3c/ADExplorerSnapshot.py/blob/590b94735db3cf18e6cc5e7512937192a1080715/adexpsnapshot/__init__.py#L205

To replicate : 
- Create an object with "New-ADComputer" (notice the dnshostname attribute is missing)
- Open in ADExplorer, create snapshot
- Run parser, check the computer.json file

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/5674190/174424673-9a8bf79c-c12d-42d1-ba60-6b8ef5ddf625.png">

**Comment by c3c** [comment]
Looking at this, computers without dnshostname are indeed being excluded by https://github.com/c3c/ADExplorerSnapshot.py/blob/590b94735db3cf18e6cc5e7512937192a1080715/adexpsnapshot/__init__.py#L299-L301

Based on how bloodhound.py does this per https://github.com/fox-it/BloodHound.py/blob/master/bloodhound/ad/computer.py#L82-L85, I'm now using `resolve_ad_entry` to fill in the hostname.

This should hopefully fix this; closing for now.
