### ISSUE TITLE
Not support for Bloodhound 4.2.0 

### ISSUE THREAD

**Issue by tlk23** [c3c/ADExplorerSnapshot.py#14]
Import Json files to Bloodhound 4.2.0 will be stuck at 77%

**Comment by AdrianVollmer** [comment]
Check the console with ctrl-shift-i while importing. This PR probably fixes it: https://github.com/c3c/ADExplorerSnapshot.py/pull/12

**Comment by c3c** [comment]
should be solved with #12 / #16 feel free to reopen if it's still an issue
