### ISSUE TITLE
Computers objects problem

### ISSUE THREAD

**Issue by soufianetahiri** [c3c/ADExplorerSnapshot.py#15]
Hello,
The import of computers stuck at some point when importing it into BH 4.2.0

**Comment by OscarAkaElvis** [comment]
same boat here, same version... the rest of json files imported ok, but computers stucks at 0%. This way

![image](https://user-images.githubusercontent.com/5803348/204800197-fd704a48-a92b-4a86-ad92-7e771cc0af4a.png)

**Comment by gelosecurity** [comment]
Seems like 4.2.0 is currently not supported, 4.1.0 works for me
