### ISSUE TITLE
`TypeError` in `processDomains` function when `level_id` is `None`

### ISSUE THREAD

**Issue by Green-Hat-Security** [c3c/ADExplorerSnapshot.py#20]
# Describe the bug
During the execution of the `processDomains` function, the script encounters a `TypeError` when trying to convert a `None` value to an integer. This occurs when the `level_id returned by `ADUtils.get_entry_property` for the property `msds-behavior-version` is `None`.

# Expected behavior
When `level_id` is `None`, the `processDomains` function should set `functional_level` to 'Unknown' and then continue with the rest of the function, without trying to cast `None` to an integer.

# Actual behavior
Even when `level_id` is `None`, the function attempts to cast it to an integer and access the `FUNCTIONAL_LEVELS` dictionary, resulting in a `TypeError`.

# Stack Trace
```python
Traceback (most recent call last):
  File "ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "adexpsnapshot/__init__.py", line 1167, in main
    ades.outputBloodHound()
  File "adexpsnapshot/__init__.py", line 139, in outputBloodHound
    self.process()
  File "adexpsnapshot/__init__.py", line 289, in process
    self.processDomains()
  File "adexpsnapshot/__init__.py", line 301, in processDomains
    functional_level = ADUtils.FUNCTIONAL_LEVELS[int(level_id)]
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

# Additional context
This error prevents the successful execution of the script and appears to be a logic error in the `processDomains` function. 
I suspect this is caused by ancient DFLs like Windows 2000.

# Proposed Solution
fixed in pull request  #19

**Comment by c3c** [comment]
Appreciate the PR, should be fixed with https://github.com/c3c/ADExplorerSnapshot.py/commit/c83d9ecd974f327b26670e3e33bc16c3feafdb7e
