### ISSUE TITLE
Python 3.11 incompatibility

### ISSUE THREAD

**Issue by goofsec** [c3c/ADExplorerSnapshot.py#25]
Since the method "_decompose" has been removed from "enum", this no longer works:
https://github.com/c3c/ADExplorerSnapshot.py/blob/38e5100ee5925e1adfe63591f9df7fb97d35ca5e/adexpsnapshot/__init__.py#L1060

Certipy has the same issue: https://github.com/ly4k/Certipy/issues/108

**Comment by c3c** [comment]
Ahh... I just ran into this about an hour ago :)
I don't know if you're in a position to test a fix for this? 
https://github.com/c3c/ADExplorerSnapshot.py/pull/26

**Comment by retronaut7** [comment]
I was having the same issue as goofsec. I tried the PR you linked and it fixed the issue. Currently on Python 3.11.2 if that helps.

**Comment by w0lfcat** [comment]
@retronaut7 I believe I'm having exactly the same problem. I'm using Kali-2023.2, Python 3.11.2.

https://cdimage.kali.org/kali-2023.2/kali-linux-2023.2-virtualbox-amd64.7z

Can you help to guide me how to use the linked PR to solve this issue?

**Comment by c3c** [comment]
I've merged the change into master.
There might still be an incorrect codeflow here related to ADCS (but we'll create a new issue for that then :))
