### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mabangde** [c3c/ADExplorerSnapshot.py#29]
python3 ADExplorerSnapshot.py result.dat -m Objects

`[◓] Collecting data: dumped 6522/212428 objects
Traceback (most recent call last):
  File "ADExplorerSnapshot.py", line 2, in <module>
    adexpsnapshot.main()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 779, in main
    ades.outputObjects()
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 102, in outputObjects
    wq.put((dict(obj.attributes.data)))
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 98, in data
    self._dico[prop.propName] = self.processAttribute(prop, entry.attrOffset, self.raw)
  File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 189, in processAttribute
    if self.log:
AttributeError: 'AttributeDict' object has no attribute 'log'`

**Comment by c3c** [comment]
looks like it is attempting to parse an ADSTYPE that isn't supported. Could you patch the following lines (189-190) to read "self.snap.log" instead?

 I'm not sure/can't remember from the top of my head whether overall parsing will be successful if this happens.

https://github.com/c3c/ADExplorerSnapshot.py/blob/a98fa5c55897f4d057f0f9d0730cf565c8b08628/adexpsnapshot/parser/classes.py#L189

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: mabangde ***@***.***>
Sent: Thursday, August 3, 2023 12:37:10 PM
To: c3c/ADExplorerSnapshot.py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [c3c/ADExplorerSnapshot.py] error (Issue #29)


python3 ADExplorerSnapshot.py result.dat -m Objects

[◓] Collecting data: dumped 6522/212428 objects Traceback (most recent call last): File "ADExplorerSnapshot.py", line 2, in <module> adexpsnapshot.main() File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 779, in main ades.outputObjects() File "/root/ADExplorerSnapshot.py/adexpsnapshot/__init__.py", line 102, in outputObjects wq.put((dict(obj.attributes.data))) File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 98, in data self._dico[prop.propName] = self.processAttribute(prop, entry.attrOffset, self.raw) File "/root/ADExplorerSnapshot.py/adexpsnapshot/parser/classes.py", line 189, in processAttribute if self.log: AttributeError: 'AttributeDict' object has no attribute 'log'

**Comment by mabangde** [comment]
fix code：

![image](https://github.com/c3c/ADExplorerSnapshot.py/assets/6219246/0d94c8ca-e16d-4097-aff1-85eb2d1c8cda)

**Comment by c3c** [comment]
Fixed with https://github.com/c3c/ADExplorerSnapshot.py/commit/6fa3dfdb87c2bae3f02f369908afbae2dcacc63a
