### ISSUE TITLE
'data' is not defined

### ISSUE THREAD

**Issue by OlafHaalstra** [c3c/ADExplorerSnapshot.py#3]
The dictionary on the following line is not defined:

https://github.com/c3c/ADExplorerSnapshot.py/blob/33708fa990d400ffd0d26d928dab33e66bf1a732/adexpsnapshot/__init__.py#L275

Pull requests coming your way.

Another issue is that the following attribute is not used, do you want to keep in in there for future use?
https://github.com/c3c/ADExplorerSnapshot.py/blob/33708fa990d400ffd0d26d928dab33e66bf1a732/adexpsnapshot/__init__.py#L225

**Comment by c3c** [comment]
Thanks for reporting this issue!
Pushed https://github.com/c3c/ADExplorerSnapshot.py/commit/977607f1ec52b471bf8df451c586c083fe9a6caa which renames `data` to `computer` and removed the `samname` variable.
