### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by caroline7714** [c3c/ADExplorerSnapshot.py#37]
hi 

I received the following error, as seen in the image below.
![Screenshot (2)](https://github.com/c3c/ADExplorerSnapshot.py/assets/147403974/03937205-9f0b-470b-a768-e2537253a9be)

I also tested it with a Python version, but I got more errors. that is displayed in the below

![Screenshot (42)](https://github.com/c3c/ADExplorerSnapshot.py/assets/147403974/e4d07a30-a6c9-4702-889e-742e3f8e29ba)

**Comment by caroline7714** [comment]
How can I get it solved?

**Comment by caroline7714** [comment]
![Uploading SharedScreenshot.jpg…]()

**Comment by caroline7714** [comment]
![Screenshot (42)](https://github.com/c3c/ADExplorerSnapshot.py/assets/147403974/3b94b299-2557-471e-89f8-c4e25cda8396)

**Comment by cyberducks17** [comment]
Hey, when I used ur fixed code in 'objects' mode, it still didn't work. (It has the same error as the guy who uploaded this issue), do you have a solution? thx

**Comment by c3c** [comment]
What Python version are you using?
The `classes` property should be present for all AD `Object`s:  https://github.com/c3c/ADExplorerSnapshot.py/blob/main/adexpsnapshot/parser/classes.py#L222. 
There might be an edge case in which either the object itself is `None` - if possible if you run into it again it would be good to dump an object in the code with a simple `print(..)` so we can have a look.

**Comment by c3c** [comment]
Underlying issue should now be fixed, and some extra error handling added.
https://github.com/c3c/ADExplorerSnapshot.py/issues/62
