### ISSUE TITLE
same error 

### ISSUE THREAD

**Issue by caroline7714** [c3c/ADExplorerSnapshot.py#38]
hi
Like you, I also have an error.
 
![Screenshot (4)](https://github.com/c3c/ADExplorerSnapshot.py/assets/147403974/8f6309d9-77f9-4b87-95b8-cb835033a963)
 version of bloodhound are 4.3 
Have you thought about it at all?

**Comment by volker-carstein** [comment]
Which version of bloodhound.py are you using ?
A quick fix I used is to downgrade to bloodhound 1.6.1 by running the following command : 
`pip3 install bloodhound==1.6.1`

**Comment by ignitionlab** [comment]
Exact same issue here.
