### ISSUE TITLE
 ADExplorerSnapshot doesn't map primaryGroupID

### ISSUE THREAD

**Issue by N7WEra** [c3c/ADExplorerSnapshot.py#6]
The script used to import ADExplorer snapshots in to Bloodhound doesn't pick up on the PrimaryGroupID attribute and therefore doesn't map the relation. This results in a users not showing as part of certain groups.
![adexplorer](https://user-images.githubusercontent.com/59871507/149753670-7c9f5d07-3a26-4f81-9fdb-cfcb4b664c96.png)

**Comment by c3c** [comment]
Thanks for reporting this! This is partly due to how `BloodHound.py` handles single-valued vs multi-valued LDAP attributes in comparison to `ADExplorerSnapshot.py`... I should find a better way to deal with those :)
Hopefully should work now - let me know if it doesn't.
